<a href="https://colab.research.google.com/github/saifshahid12/Numpy-practice/blob/main/Indexing_with_boolean_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Create array of random number :**

In [ ]:
import numpy as np
# genearte randome number array
# 1 to 100 with 20 items

arr1 = np.random.randint(low =1 , high = 100 , size =20).reshape(4,5)
arr1

array([[72, 61, 62, 33,  3],
       [79,  1, 88, 91, 89],
       [17, 28, 32, 47, 51],
       [66, 98, 37, 39, 76]])

**get row or colums using index :**

In [ ]:
# get row and number of row from array

arr1[0][3]       # 0 is index of row and 3 is index of 3rd number in 0 row

np.int64(33)

**Conditional indexing :**

In [ ]:
# this is boolean method
# use condition if greater or less then number
# out put will be true and false
arr1>50

array([72, 61, 62, 79, 88, 91, 89, 51, 66, 98, 76])

**Overlaping in existing :**

In [ ]:
# overlaping in existig code
# chek if there is trues false
# show true values in outpu
# using verlaping method

arr1[arr1>50]

array([72, 61, 62, 79, 88, 91, 89, 51, 66, 98, 76])

**select great number form existing code:**

In [ ]:
# select great numbers which great then 50 and must be odd

arr1[(arr1>50) & (arr1%2!=0)] # modulus formula use for odd number


array([61, 79, 91, 89, 51])

**make zero number in the array:**

In [ ]:
# make number 0 which is greter then 50 and is odd
# take from existing code

arr1[(arr1>50)&(arr1%2!=0)]=0
arr1

array([[72,  0, 62, 33,  3],
       [ 0,  1, 88,  0,  0],
       [17, 28, 32, 47,  0],
       [66, 98, 37, 39, 76]])