<a href="https://colab.research.google.com/github/saifshahid12/Numpy-practice/blob/main/Indexing%2CSlicing%2CIteration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Index , Slicing , iteration**





**1 Create array :**

In [ ]:
# Create array in arange method
import numpy as np
arr1 = np.arange(24)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

**2 use ,reshape method ():**

In [ ]:
# use reshape method
# we make row and columns :
arr2 = arr1.reshape(6,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

**find numbers through index and slicing:**

In [ ]:
# give index two which is in row wise
# arr2[2]         # output is [8,9,10,11]
# arr2[:2]        # output is 1st 2 rows
# arr2[:,2]         # find third column : output is [2,6,10,14,18,22]
# arr2[:,1:3]         find index 1 colum and index 2 colum: out put is 1 and 2 index

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

**Iteration :**

In [ ]:
# create array with exisiting
# iteration

arr3 = arr2
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#  iteration in array using for loop with np.nditer()
#  it print numbers in asending order
for i in np.nditer(arr3):
       print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
