<a href="https://colab.research.google.com/github/saifshahid12/Numpy-practice/blob/main/Numpy_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Create array and subtract it:**

In [ ]:
import numpy as np
# create two arrays and subtract into it :

arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([2,13,4,5,6,5])

arr1-arr2



array([ -1, -11,  -1,  -1,  -1,   1])

**Create array and multiply both :**

In [ ]:
# create two arrays and multiply it

arr3 = np.array([1,2,3,4,5,6])
arr4 = np.array([2,13,4,5,6,5])
# arr3*arr4
arr3*3               # only multiply with three output is [3,6,9,12,15,18]

array([ 3,  6,  9, 12, 15, 18])

**Create array and find theier greatest:**

In [ ]:
# taked tow arrays and find the greater array
# out put is in true and false

arr5 = np.array([1,2,30,4,50,6,7])
arr6 = np.array([2,13,4,5,6,5])
arr5>6


array([False, False,  True, False,  True, False,  True])

Create array and use dot function:

In [ ]:
# create two arrays
# use dot function in matrices multipliation

arr7 = np.arange(6).reshape(2,3)
arr8 = np.arange(6,12) .reshape(3,2)
arr7.dot(arr8)

array([[ 28,  31],
       [100, 112]])