<a href="https://colab.research.google.com/github/saifshahid12/Numpy-practice/blob/main/numpy_liabrary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**METHODS OF CREATING ARRAYS :**

In [ ]:
# creating numpy n-d arrays :
import numpy as np


**1 Array :**


In [ ]:
# create array:  1-D
arr1 =np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [ ]:
# check type :
type(arr1)    # output .ndarray

numpy.ndarray

**2 Creating two dimensional array :**

In [ ]:
# create two domensional array by passing two lists :
# 2-D
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

***3 Create Array through zeros() :***



In [ ]:
# create array using zero method :
# 2 row and 3 is colum
arr3 = np.zeros([2,3])         # initialize with 0
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

**4 Create Arrys through ones():**

In [ ]:
# create array using ones method :
# 3 is row and 3 is colum
arr4 =np.ones([3,3])         # initialize with 1
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**5 Create array through Identity ()**

In [ ]:
#  create array using identity func
#  identity matrix is kind of square matrix that acts like the number 1

arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**6 Create array using arange ()**

In [ ]:
# generate number grom 5,to 15 using arange func
# make list of numbers
arr6 = np.arange(5,16)
arr6

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

**7 Create array through linspace func()**


In [ ]:
# create aray using linspace
# by default 10 to 20 have 11 values but start from 10 to 20 and contain just 10 values
# show te space in this .

arr7 = np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

**8 Create array through copy ()**





In [ ]:
# create array using copy method
# it will copy the given value from existing
arr8 =arr3.copy()
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

**Properties and Attributes :**



1 Shape :

In [ ]:
# create array and find the shape
# shape work on array that how much row and colums

arr1 =np.array([1,2,3,4,5])
arr1.shape

(5,)

In [ ]:
# create 2-d array and find the shape of it
# now 2 is row and 3 is colum
arr2 = np.array([[1,2,3],[4,5,6]])
arr2.shape

(2, 3)

2 Create 3-D array and find shape

In [ ]:
#  find shape
arr9 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr9


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
arr9.shape  # shape 2 colum 2 rows

(2, 2, 2)

3 create array and find ndim

In [ ]:
# create array and find demention using ndim
# 2 dimention array
arr10 = np.array([[1,2,3],[4,5,6]])
arr10.ndim

2

4 Create 3-D array and find its dimention using ndim

In [ ]:
# create 3-D array and find its demention using ndim
# this is 3 dimention array
arr11 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr11.ndim


3

5 Create array and find its size using size:

In [ ]:
# create aray and find size using size method
# size is use for counting the values in array

arr12 = np.array([1,2,3,4,5])
arr12.size           # out put is 5

5

6 create aray and find the item size :

In [ ]:
# create array and find itemsize
# itemsize is use for how much item in array .like how much lists quantity
arr13 = np.array([[1,2,3],[3,4,6]])
arr13.itemsize             # itemsze is two due to 2 brakets


8

7 Check the dtype of programe 13

In [ ]:
# chek the dtype of 13 programe

arr13.dtype

dtype('int64')

8 create array and check astype :


In [ ]:
# create an array and change types
# this is int and change into float
# change astyype from int to float
arr14 =np.array([1,2,3,4,5])
arr14

array([1, 2, 3, 4, 5])

In [ ]:
# change astype from int to float :

arr14.astype("float")

array([1., 2., 3., 4., 5.])