<a href="https://colab.research.google.com/github/saifshahid12/Numpy-practice/blob/main/Reshaping_Numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1 Create array , use Ravel method for Reshape array**

In [ ]:
import numpy as np
arr1 = np.array([[1,2,3,4,8],[1,6,8,9,7,]])
arr1

array([[1, 2, 3, 4, 8],
       [1, 6, 8, 9, 7]])

**2 use Ravel function :**

In [ ]:
# ravel function use for writing in list form
arr1.ravel()

array([1, 2, 3, 4, 8, 1, 6, 8, 9, 7])

**3 Use transpose function :**

In [ ]:
# create array and use transpose function
# transpose funct use for change colum into row and row into column

arr2 = np.array([[1,2,3,4,8],[1,6,8,9,7,]])
arr2.transpose()

array([[1, 1],
       [2, 6],
       [3, 8],
       [4, 9],
       [8, 7]])

**4 create array and combine it using hstack func ()**

In [ ]:
# create two arratys and cobine it
# use hstack func()
# it will write in just one line
arr3 = np.array([1,2,3,4,8])
arr4 = np.array([1,6,8,9,7,])

# two methods for using hstack function

np.hstack([arr3, arr4])
          # OR
# arr3.hstack(arr4)

array([1, 2, 3, 4, 8, 1, 6, 8, 9, 7])

In [ ]:
arr5= np.array([1,2,3,4,8])
arr6 = np.array([1,6,8,9,7,])
combine=np.hstack([arr5, arr6])
arr5_new, arr6_new = np.hsplit(combine,[len(arr5)])

In [ ]:
arr5_new, arr6_new = np.hsplit(combine, [len(arr5)])
print(arr5_new,arr6_new)


[1 2 3 4 8] [1 6 8 9 7]
